### ISSUE TITLE
Download of tag crashes

### ISSUE THREAD

**Issue by SciLor** [toniebox-reverse-engineering/teddycloud#121]
This problem is triggered when I try to download a tonie over the webinterface where the tags memory and ruid is in the .json
This only occurs on my production server on v0.3.4 
It does not happen on the latest develop from today.
```
==8==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x615000050280 at pc 0x562406a93555 bp 0x7f6f7bdfca40 sp 0x7f6f7bdfc1e8
READ of size 513 at 0x615000050280 thread T3
    #0 0x562406a93554 in __interceptor_strchr.part.0 (/usr/local/bin/teddycloud+0x589554)
    #1 0x562406fa1ece in socketReceive src/platform/platform_linux.c:274
    #2 0x562406d39ad1 in httpReceive src/cyclone/cyclone_tcp/http/http_server_misc.c:1052
    #3 0x562406d39ad1 in httpReadHeaderField src/cyclone/cyclone_tcp/http/http_server_misc.c:371
    #4 0x562406d3e930 in httpReadRequestHeader src/cyclone/cyclone_tcp/http/http_server_misc.c:150
    #5 0x562406d37ee4 in httpConnectionTask src/cyclone/cyclone_tcp/http/http_server.c:461
    #6 0x7f6f804fcac2  (/lib/x86_64-linux-gnu/libc.so.6+0x94ac2)
    #7 0x7f6f8058d813 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x125813)

0x615000050280 is located 0 bytes to the right of 512-byte region [0x615000050080,0x615000050280)
allocated by thread T3 here:
    #0 0x562406b09e57 in malloc (/usr/local/bin/teddycloud+0x5ffe57)
    #1 0x562406fa2107 in socketReceive src/platform/platform_linux.c:257

Thread T3 created by T0 here:
    #0 0x562406aadc75 in __interceptor_pthread_create (/usr/local/bin/teddycloud+0x5a3c75)
    #1 0x562406fa3f03 in osCreateTask src/cyclone/common/os_port_posix.c:87

SUMMARY: AddressSanitizer: heap-buffer-overflow (/usr/local/bin/teddycloud+0x589554) in __interceptor_strchr.part.0
Shadow bytes around the buggy address:
  0x0c2a80002000: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c2a80002010: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c2a80002020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c2a80002030: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c2a80002040: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c2a80002050:[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c2a80002060: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c2a80002070: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c2a80002080: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c2a80002090: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c2a800020a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==8==ABORTING
```

**Comment by SciLor** [comment]
https://github.com/toniebox-reverse-engineering/teddycloud/commit/906c807f4fe3ade8a457d85732f8027ff594fa74
