### ISSUE TITLE
Fix memory leak on esp32 extraction via cli

### ISSUE THREAD

**Issue by SciLor** [toniebox-reverse-engineering/teddycloud#222]
drwxrwxrwx 4 root   root      4096 Oct  9 08:47 client
drwxrwxrwx 2 root   root      4096 Oct  9 08:01 server
-rwxrwxrwx 1 ubuntu ubuntu 8388608 Oct  9 08:33 tb.esp32.bin
root@teddycloud:/teddycloud/certs# teddycloud --esp32-extract tb.esp32.bin --destination client/esp32
TeddyCloud v0.6.1 (0411205) - 2024-10-05 12:58:04 +0000 ubuntu linux-x86_64(64)

[options] specified 'esp32_extract' as 'tb.esp32.bin'
[options] specified 'destination' as 'client/esp32'
INFO |settings.c:0828:settings_load_ovl()| Load settings from /teddycloud/certs/config/config.overlay.ini
WARN |settings.c:0836:settings_load_ovl()| Config file does not exist, creating it...
INFO |settings.c:0724:settings_save_ovl()| Save settings to /teddycloud/certs/config/config.overlay.ini
ERROR|settings.c:0728:settings_save_ovl()| Failed to open config file for writing
INFO |settings.c:0828:settings_load_ovl()| Load settings from /teddycloud/certs/config/config.ini
WARN |settings.c:0836:settings_load_ovl()| Config file does not exist, creating it...
INFO |settings.c:0724:settings_save_ovl()| Save settings to /teddycloud/certs/config/config.ini
ERROR|settings.c:0728:settings_save_ovl()| Failed to open config file for writing
INFO |settings.c:0828:settings_load_ovl()| Load settings from /etc/teddycloud/config/config.overlay.ini
INFO |settings.c:0828:settings_load_ovl()| Load settings from /etc/teddycloud/config/config.ini
INFO |settings.c:0828:settings_load_ovl()| Load settings from /etc/teddycloud/config/config.overlay.ini
INFO |esp32.c:1380:esp32_get_partition()| Search for partition 'assets'
INFO |esp32.c:1399:esp32_get_partition()| Found partition 'assets' at 0x00F000
INFO |esp32.c:1102:esp32_fat_extract_folder()| Write 'CERT\CA.DER to 'client/esp32/CA.DER' (1419 bytes)
INFO |esp32.c:1102:esp32_fat_extract_folder()| Write 'CERT\CLIENT.DER to 'client/esp32/CLIENT.DER' (1030 bytes)
INFO |esp32.c:1102:esp32_fat_extract_folder()| Write 'CERT\PRIVATE.DER to 'client/esp32/PRIVATE.DER' (1193 bytes)

=================================================================
==122==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 454 byte(s) in 59 object(s) allocated from:
    #0 0x560079fc62e7 in strdup (/usr/local/bin/teddycloud+0x6482e7)
    #1 0x56007a159371 in settings_init_opt src/settings.c:650
    #2 0x56007a16979c in settings_init src/settings.c:676
    #3 0x56007a120346 in main_init_settings src/main.c:159
    #4 0x560079f855ec in main src/main.c:358
    #5 0x7f13ce2281c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9)
    #6 0x7f13ce22828a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a)
    #7 0x560079f8f454 in _start (/usr/local/bin/teddycloud+0x611454)

**Comment by baflo** [comment]
Hi,

I want to add (hope it helps), that I experienced memory leaks, when I tried to run TeddyCloud as an Home Assistant addon on an Intel NUC6CAYH, which runs on a Celeron J3455.



```
TeddyCloud vX.X.X (9930675) - 2024-11-14 20:10:20 +0000 ubuntu linux-x86_64(64)

INFO |settings.c:0849:settings_load_ovl| Load settings from /data/teddycloud/config/config.overlay.ini
WARN |settings.c:0857:settings_load_ovl| Config file does not exist, creating it...
INFO |settings.c:0745:settings_save_ovl| Save settings to /data/teddycloud/config/config.overlay.ini
ERROR|settings.c:0749:settings_save_ovl| Failed to open config file for writing
INFO |settings.c:0849:settings_load_ovl| Load settings from /data/teddycloud/config/config.ini
WARN |settings.c:0857:settings_load_ovl| Config file does not exist, creating it...
INFO |settings.c:0745:settings_save_ovl| Save settings to /data/teddycloud/config/config.ini
ERROR|settings.c:0749:settings_save_ovl| Failed to open config file for writing
INFO |settings.c:0849:settings_load_ovl| Load settings from /etc/teddycloud/config/config.overlay.ini
WARN |settings.c:0857:settings_load_ovl| Config file does not exist, creating it...
INFO |settings.c:0745:settings_save_ovl| Save settings to /etc/teddycloud/config/config.overlay.ini
ERROR|settings.c:0749:settings_save_ovl| Failed to open config file for writing
INFO |settings.c:0849:settings_load_ovl| Load settings from /etc/teddycloud/config/config.ini
WARN |settings.c:0857:settings_load_ovl| Config file does not exist, creating it...
INFO |settings.c:0745:settings_save_ovl| Save settings to /etc/teddycloud/config/config.ini
ERROR|settings.c:0749:settings_save_ovl| Failed to open config file for writing
ERROR|main.c:0183:main_init_settings| ERROR: settings_init() failed with error Directory not found [308]
ERROR|main.c:0184:main_init_settings| ERROR: Make sure the config path exists and is writable

=================================================================
==10==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 454 byte(s) in 59 object(s) allocated from:
    #0 0x55a68c04e867 in __interceptor_strdup (/usr/local/bin/teddycloud+0x64d867)
    #1 0x55a68c1e5021 in settings_init_opt src/settings.c:662
    #2 0x55a68c1f544c in settings_init src/settings.c:688
    #3 0x55a68c1ab026 in main_init_settings src/main.c:159
    #4 0x55a68c00db2c in main src/main.c:365
    #5 0x7f00641691c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9)
    #6 0x7f006416928a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a)
    #7 0x55a68c0179d4 in _start (/usr/local/bin/teddycloud+0x6169d4)

Direct leak of 256 byte(s) in 1 object(s) allocated from:
    #0 0x55a68c0a7727 in __interceptor_malloc (/usr/local/bin/teddycloud+0x6a6727)
    #1 0x55a68c1e9b90 in settings_generate_internal_dirs src/settings.c:517
    #2 0x55a68c1f1dfd in settings_changed_id src/settings.c:553
    #3 0x55a68c1f56f9 in settings_changed src/settings.c:545
    #4 0x55a68c1f56f9 in settings_init src/settings.c:721
    #5 0x55a68c1ab026 in main_init_settings src/main.c:159
    #6 0x55a68c00db2c in main src/main.c:365
    #7 0x7f00641691c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9)
    #8 0x7f006416928a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a)
    #9 0x55a68c0179d4 in _start (/usr/local/bin/teddycloud+0x6169d4)

Direct leak of 256 byte(s) in 1 object(s) allocated from:
    #0 0x55a68c0a7727 in __interceptor_malloc (/usr/local/bin/teddycloud+0x6a6727)
    #1 0x55a68c1e9b2c in settings_generate_internal_dirs src/settings.c:515
    #2 0x55a68c1f1dfd in settings_changed_id src/settings.c:553
    #3 0x55a68c1f56f9 in settings_changed src/settings.c:545
    #4 0x55a68c1f56f9 in settings_init src/settings.c:721
    #5 0x55a68c1ab026 in main_init_settings src/main.c:159
    #6 0x55a68c00db2c in main src/main.c:365
    #7 0x7f00641691c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9)
    #8 0x7f006416928a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a)
    #9 0x55a68c0179d4 in _start (/usr/local/bin/teddycloud+0x6169d4)

Direct leak of 256 byte(s) in 1 object(s) allocated from:
    #0 0x55a68c0a7727 in __interceptor_malloc (/usr/local/bin/teddycloud+0x6a6727)
    #1 0x55a68c1e9a9a in settings_generate_internal_dirs src/settings.c:512
    #2 0x55a68c1f1dfd in settings_changed_id src/settings.c:553
    #3 0x55a68c1f56f9 in settings_changed src/settings.c:545
    #4 0x55a68c1f56f9 in settings_init src/settings.c:721
    #5 0x55a68c1ab026 in main_init_settings src/main.c:159
    #6 0x55a68c00db2c in main src/main.c:365
    #7 0x7f00641691c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9)
    #8 0x7f006416928a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a)
    #9 0x55a68c0179d4 in _start (/usr/local/bin/teddycloud+0x6169d4)

Direct leak of 256 byte(s) in 1 object(s) allocated from:
    #0 0x55a68c0a7727 in __interceptor_malloc (/usr/local/bin/teddycloud+0x6a6727)
    #1 0x55a68c1e9a68 in settings_generate_internal_dirs src/settings.c:511
    #2 0x55a68c1f1dfd in settings_changed_id src/settings.c:553
    #3 0x55a68c1f56f9 in settings_changed src/settings.c:545
    #4 0x55a68c1f56f9 in settings_init src/settings.c:721
    #5 0x55a68c1ab026 in main_init_settings src/main.c:159
    #6 0x55a68c00db2c in main src/main.c:365
    #7 0x7f00641691c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9)
    #8 0x7f006416928a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a)
    #9 0x55a68c0179d4 in _start (/usr/local/bin/teddycloud+0x6169d4)

Direct leak of 256 byte(s) in 1 object(s) allocated from:
    #0 0x55a68c0a7727 in __interceptor_malloc (/usr/local/bin/teddycloud+0x6a6727)
    #1 0x55a68c1e9bbe in settings_generate_internal_dirs src/settings.c:518
    #2 0x55a68c1f1dfd in settings_changed_id src/settings.c:553
    #3 0x55a68c1f56f9 in settings_changed src/settings.c:545
    #4 0x55a68c1f56f9 in settings_init src/settings.c:721
    #5 0x55a68c1ab026 in main_init_settings src/main.c:159
    #6 0x55a68c00db2c in main src/main.c:365
    #7 0x7f00641691c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9)
    #8 0x7f006416928a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a)
    #9 0x55a68c0179d4 in _start (/usr/local/bin/teddycloud+0x6169d4)

Direct leak of 256 byte(s) in 1 object(s) allocated from:
    #0 0x55a68c0a7727 in __interceptor_malloc (/usr/local/bin/teddycloud+0x6a6727)
    #1 0x55a68c1e9b5e in settings_generate_internal_dirs src/settings.c:516
    #2 0x55a68c1f1dfd in settings_changed_id src/settings.c:553
    #3 0x55a68c1f56f9 in settings_changed src/settings.c:545
    #4 0x55a68c1f56f9 in settings_init src/settings.c:721
    #5 0x55a68c1ab026 in main_init_settings src/main.c:159
    #6 0x55a68c00db2c in main src/main.c:365
    #7 0x7f00641691c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9)
    #8 0x7f006416928a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a)
    #9 0x55a68c0179d4 in _start (/usr/local/bin/teddycloud+0x6169d4)

Direct leak of 256 byte(s) in 1 object(s) allocated from:
    #0 0x55a68c0a7727 in __interceptor_malloc (/usr/local/bin/teddycloud+0x6a6727)
    #1 0x55a68c1e9bf0 in settings_generate_internal_dirs src/settings.c:519
    #2 0x55a68c1f1dfd in settings_changed_id src/settings.c:553
    #3 0x55a68c1f56f9 in settings_changed src/settings.c:545
    #4 0x55a68c1f56f9 in settings_init src/settings.c:721
    #5 0x55a68c1ab026 in main_init_settings src/main.c:159
    #6 0x55a68c00db2c in main src/main.c:365
    #7 0x7f00641691c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9)
    #8 0x7f006416928a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a)
    #9 0x55a68c0179d4 in _start (/usr/local/bin/teddycloud+0x6169d4)

Direct leak of 256 byte(s) in 1 object(s) allocated from:
    #0 0x55a68c0a7727 in __interceptor_malloc (/usr/local/bin/teddycloud+0x6a6727)
    #1 0x55a68c1e9ac8 in settings_generate_internal_dirs src/settings.c:513
    #2 0x55a68c1f1dfd in settings_changed_id src/settings.c:553
    #3 0x55a68c1f56f9 in settings_changed src/settings.c:545
    #4 0x55a68c1f56f9 in settings_init src/settings.c:721
    #5 0x55a68c1ab026 in main_init_settings src/main.c:159
    #6 0x55a68c00db2c in main src/main.c:365
    #7 0x7f00641691c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9)
    #8 0x7f006416928a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a)
    #9 0x55a68c0179d4 in _start (/usr/local/bin/teddycloud+0x6169d4)

Direct leak of 256 byte(s) in 1 object(s) allocated from:
    #0 0x55a68c0a7727 in __interceptor_malloc (/usr/local/bin/teddycloud+0x6a6727)
    #1 0x55a68c1e9afa in settings_generate_internal_dirs src/settings.c:514
    #2 0x55a68c1f1dfd in settings_changed_id src/settings.c:553
    #3 0x55a68c1f56f9 in settings_changed src/settings.c:545
    #4 0x55a68c1f56f9 in settings_init src/settings.c:721
    #5 0x55a68c1ab026 in main_init_settings src/main.c:159
    #6 0x55a68c00db2c in main src/main.c:365
    #7 0x7f00641691c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9)
    #8 0x7f006416928a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a)
    #9 0x55a68c0179d4 in _start (/usr/local/bin/teddycloud+0x6169d4)

Direct leak of 256 byte(s) in 1 object(s) allocated from:
    #0 0x55a68c0a7727 in __interceptor_malloc (/usr/local/bin/teddycloud+0x6a6727)
    #1 0x55a68c1e9c22 in settings_generate_internal_dirs src/settings.c:520
    #2 0x55a68c1f1dfd in settings_changed_id src/settings.c:553
    #3 0x55a68c1f56f9 in settings_changed src/settings.c:545
    #4 0x55a68c1f56f9 in settings_init src/settings.c:721
    #5 0x55a68c1ab026 in main_init_settings src/main.c:159
    #6 0x55a68c00db2c in main src/main.c:365
    #7 0x7f00641691c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9)
    #8 0x7f006416928a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a)
    #9 0x55a68c0179d4 in _start (/usr/local/bin/teddycloud+0x6169d4)

Direct leak of 114 byte(s) in 1 object(s) allocated from:
    #0 0x55a68c04e867 in __interceptor_strdup (/usr/local/bin/teddycloud+0x64d867)
    #1 0x55a68c1f379f in settings_set_string_id src/settings.c:1411
    #2 0x55a68c1f561f in settings_set_string_id src/settings.c:1397
    #3 0x55a68c1f561f in settings_set_string src/settings.c:1389
    #4 0x55a68c1f561f in settings_init src/settings.c:704
    #5 0x55a68c1ab026 in main_init_settings src/main.c:159
    #6 0x55a68c00db2c in main src/main.c:365
    #7 0x7f00641691c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9)
    #8 0x7f006416928a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a)
    #9 0x55a68c0179d4 in _start (/usr/local/bin/teddycloud+0x6169d4)

Direct leak of 93 byte(s) in 1 object(s) allocated from:
    #0 0x55a68c04e867 in __interceptor_strdup (/usr/local/bin/teddycloud+0x64d867)
    #1 0x55a68c1f379f in settings_set_string_id src/settings.c:1411
    #2 0x55a68c1f56bd in settings_set_string_id src/settings.c:1397
    #3 0x55a68c1f56bd in settings_set_string src/settings.c:1389
    #4 0x55a68c1f56bd in settings_init src/settings.c:713
    #5 0x55a68c1ab026 in main_init_settings src/main.c:159
    #6 0x55a68c00db2c in main src/main.c:365
    #7 0x7f00641691c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9)
    #8 0x7f006416928a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a)
    #9 0x55a68c0179d4 in _start (/usr/local/bin/teddycloud+0x6169d4)

Direct leak of 80 byte(s) in 1 object(s) allocated from:
    #0 0x55a68c04e867 in __interceptor_strdup (/usr/local/bin/teddycloud+0x64d867)
    #1 0x55a68c1f379f in settings_set_string_id src/settings.c:1411
    #2 0x55a68c1f560a in settings_set_string_id src/settings.c:1397
    #3 0x55a68c1f560a in settings_set_string src/settings.c:1389
    #4 0x55a68c1f560a in settings_init src/settings.c:703
    #5 0x55a68c1ab026 in main_init_settings src/main.c:159
    #6 0x55a68c00db2c in main src/main.c:365
    #7 0x7f00641691c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9)
    #8 0x7f006416928a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a)
    #9 0x55a68c0179d4 in _start (/usr/local/bin/teddycloud+0x6169d4)

Direct leak of 60 byte(s) in 1 object(s) allocated from:
    #0 0x55a68c04e867 in __interceptor_strdup (/usr/local/bin/teddycloud+0x64d867)
    #1 0x55a68c1f379f in settings_set_string_id src/settings.c:1411
    #2 0x55a68c1f56a8 in settings_set_string_id src/settings.c:1397
    #3 0x55a68c1f56a8 in settings_set_string src/settings.c:1389
    #4 0x55a68c1f56a8 in settings_init src/settings.c:712
    #5 0x55a68c1ab026 in main_init_settings src/main.c:159
    #6 0x55a68c00db2c in main src/main.c:365
    #7 0x7f00641691c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9)
    #8 0x7f006416928a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a)
    #9 0x55a68c0179d4 in _start (/usr/local/bin/teddycloud+0x6169d4)

Direct leak of 41 byte(s) in 1 object(s) allocated from:
    #0 0x55a68c04e867 in __interceptor_strdup (/usr/local/bin/teddycloud+0x64d867)
    #1 0x55a68c1f379f in settings_set_string_id src/settings.c:1411
    #2 0x55a68c1f5580 in settings_set_string_id src/settings.c:1397
    #3 0x55a68c1f5580 in settings_set_string src/settings.c:1389
    #4 0x55a68c1f5580 in settings_init src/settings.c:696
    #5 0x55a68c1ab026 in main_init_settings src/main.c:159
    #6 0x55a68c00db2c in main src/main.c:365
    #7 0x7f00641691c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9)
    #8 0x7f006416928a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a)
    #9 0x55a68c0179d4 in _start (/usr/local/bin/teddycloud+0x6169d4)

Direct leak of 41 byte(s) in 1 object(s) allocated from:
    #0 0x55a68c04e867 in __interceptor_strdup (/usr/local/bin/teddycloud+0x64d867)
    #1 0x55a68c1f379f in settings_set_string_id src/settings.c:1411
    #2 0x55a68c1f565d in settings_set_string_id src/settings.c:1397
    #3 0x55a68c1f565d in settings_set_string src/settings.c:1389
    #4 0x55a68c1f565d in settings_init src/settings.c:708
    #5 0x55a68c1ab026 in main_init_settings src/main.c:159
    #6 0x55a68c00db2c in main src/main.c:365
    #7 0x7f00641691c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9)
    #8 0x7f006416928a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a)
    #9 0x55a68c0179d4 in _start (/usr/local/bin/teddycloud+0x6169d4)

Direct leak of 26 byte(s) in 1 object(s) allocated from:
    #0 0x55a68c04e867 in __interceptor_strdup (/usr/local/bin/teddycloud+0x64d867)
    #1 0x55a68c1f379f in settings_set_string_id src/settings.c:1411
    #2 0x55a68c1f567e in settings_set_string_id src/settings.c:1397
    #3 0x55a68c1f567e in settings_set_string src/settings.c:1389
    #4 0x55a68c1f567e in settings_init src/settings.c:710
    #5 0x55a68c1ab026 in main_init_settings src/main.c:159
    #6 0x55a68c00db2c in main src/main.c:365
    #7 0x7f00641691c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9)
    #8 0x7f006416928a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a)
    #9 0x55a68c0179d4 in _start (/usr/local/bin/teddycloud+0x6169d4)

Direct leak of 26 byte(s) in 1 object(s) allocated from:
    #0 0x55a68c04e867 in __interceptor_strdup (/usr/local/bin/teddycloud+0x64d867)
    #1 0x55a68c1f379f in settings_set_string_id src/settings.c:1411
    #2 0x55a68c1f55a1 in settings_set_string_id src/settings.c:1397
    #3 0x55a68c1f55a1 in settings_set_string src/settings.c:1389
    #4 0x55a68c1f55a1 in settings_init src/settings.c:698
    #5 0x55a68c1ab026 in main_init_settings src/main.c:159
    #6 0x55a68c00db2c in main src/main.c:365
    #7 0x7f00641691c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9)
    #8 0x7f006416928a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a)
    #9 0x55a68c0179d4 in _start (/usr/local/bin/teddycloud+0x6169d4)

Direct leak of 22 byte(s) in 1 object(s) allocated from:
    #0 0x55a68c04e867 in __interceptor_strdup (/usr/local/bin/teddycloud+0x64d867)
    #1 0x55a68c1f379f in settings_set_string_id src/settings.c:1411
    #2 0x55a68c1f5693 in settings_set_string_id src/settings.c:1397
    #3 0x55a68c1f5693 in settings_set_string src/settings.c:1389
    #4 0x55a68c1f5693 in settings_init src/settings.c:711
    #5 0x55a68c1ab026 in main_init_settings src/main.c:159
    #6 0x55a68c00db2c in main src/main.c:365
    #7 0x7f00641691c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9)
    #8 0x7f006416928a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a)
    #9 0x55a68c0179d4 in _start (/usr/local/bin/teddycloud+0x6169d4)

Direct leak of 18 byte(s) in 1 object(s) allocated from:
    #0 0x55a68c04e867 in __interceptor_strdup (/usr/local/bin/teddycloud+0x64d867)
    #1 0x55a68c1f379f in settings_set_string_id src/settings.c:1411
    #2 0x55a68c1f55f5 in settings_set_string_id src/settings.c:1397
    #3 0x55a68c1f55f5 in settings_set_string src/settings.c:1389
    #4 0x55a68c1f55f5 in settings_init src/settings.c:702
    #5 0x55a68c1ab026 in main_init_settings src/main.c:159
    #6 0x55a68c00db2c in main src/main.c:365
    #7 0x7f00641691c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9)
    #8 0x7f006416928a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a)
    #9 0x55a68c0179d4 in _start (/usr/local/bin/teddycloud+0x6169d4)

Direct leak of 17 byte(s) in 1 object(s) allocated from:
    #0 0x55a68c04e867 in __interceptor_strdup (/usr/local/bin/teddycloud+0x64d867)
    #1 0x55a68c1f379f in settings_set_string_id src/settings.c:1411
    #2 0x55a68c1f5525 in settings_set_string_id src/settings.c:1397
    #3 0x55a68c1f5525 in settings_set_string src/settings.c:1389
    #4 0x55a68c1f5525 in settings_init src/settings.c:691
    #5 0x55a68c1ab026 in main_init_settings src/main.c:159
    #6 0x55a68c00db2c in main src/main.c:365
    #7 0x7f00641691c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9)
    #8 0x7f006416928a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a)
    #9 0x55a68c0179d4 in _start (/usr/local/bin/teddycloud+0x6169d4)

Direct leak of 8 byte(s) in 1 object(s) allocated from:
    #0 0x55a68c04e867 in __interceptor_strdup (/usr/local/bin/teddycloud+0x64d867)
    #1 0x55a68c1f379f in settings_set_string_id src/settings.c:1411
    #2 0x55a68c1f556b in settings_set_string_id src/settings.c:1397
    #3 0x55a68c1f556b in settings_set_string src/settings.c:1389
    #4 0x55a68c1f556b in settings_init src/settings.c:695
    #5 0x55a68c1ab026 in main_init_settings src/main.c:159
    #6 0x55a68c00db2c in main src/main.c:365
    #7 0x7f00641691c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9)
    #8 0x7f006416928a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a)
    #9 0x55a68c0179d4 in _start (/usr/local/bin/teddycloud+0x6169d4)

Direct leak of 8 byte(s) in 1 object(s) allocated from:
    #0 0x55a68c04e867 in __interceptor_strdup (/usr/local/bin/teddycloud+0x64d867)
    #1 0x55a68c1f379f in settings_set_string_id src/settings.c:1411
    #2 0x55a68c1f5648 in settings_set_string_id src/settings.c:1397
    #3 0x55a68c1f5648 in settings_set_string src/settings.c:1389
    #4 0x55a68c1f5648 in settings_init src/settings.c:707
    #5 0x55a68c1ab026 in main_init_settings src/main.c:159
    #6 0x55a68c00db2c in main src/main.c:365
    #7 0x7f00641691c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9)
    #8 0x7f006416928a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a)
    #9 0x55a68c0179d4 in _start (/usr/local/bin/teddycloud+0x6169d4)

Direct leak of 7 byte(s) in 1 object(s) allocated from:
    #0 0x55a68c04e867 in __interceptor_strdup (/usr/local/bin/teddycloud+0x64d867)
    #1 0x55a68c1f379f in settings_set_string_id src/settings.c:1411
    #2 0x55a68c1f55e0 in settings_set_string_id src/settings.c:1397
    #3 0x55a68c1f55e0 in settings_set_string src/settings.c:1389
    #4 0x55a68c1f55e0 in settings_init src/settings.c:701
    #5 0x55a68c1ab026 in main_init_settings src/main.c:159
    #6 0x55a68c00db2c in main src/main.c:365
    #7 0x7f00641691c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9)
    #8 0x7f006416928a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a)
    #9 0x55a68c0179d4 in _start (/usr/local/bin/teddycloud+0x6169d4)

Direct leak of 7 byte(s) in 1 object(s) allocated from:
    #0 0x55a68c04e867 in __interceptor_strdup (/usr/local/bin/teddycloud+0x64d867)
    #1 0x55a68c1f379f in settings_set_string_id src/settings.c:1411
    #2 0x55a68c1f5556 in settings_set_string_id src/settings.c:1397
    #3 0x55a68c1f5556 in settings_set_string src/settings.c:1389
    #4 0x55a68c1f5556 in settings_init src/settings.c:694
    #5 0x55a68c1ab026 in main_init_settings src/main.c:159
    #6 0x55a68c00db2c in main src/main.c:365
    #7 0x7f00641691c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9)
    #8 0x7f006416928a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a)
    #9 0x55a68c0179d4 in _start (/usr/local/bin/teddycloud+0x6169d4)

Direct leak of 7 byte(s) in 1 object(s) allocated from:
    #0 0x55a68c04e867 in __interceptor_strdup (/usr/local/bin/teddycloud+0x64d867)
    #1 0x55a68c1f379f in settings_set_string_id src/settings.c:1411
    #2 0x55a68c1f5633 in settings_set_string_id src/settings.c:1397
    #3 0x55a68c1f5633 in settings_set_string src/settings.c:1389
    #4 0x55a68c1f5633 in settings_init src/settings.c:706
    #5 0x55a68c1ab026 in main_init_settings src/main.c:159
    #6 0x55a68c00db2c in main src/main.c:365
    #7 0x7f00641691c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9)
    #8 0x7f006416928a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a)
    #9 0x55a68c0179d4 in _start (/usr/local/bin/teddycloud+0x6169d4)

Direct leak of 6 byte(s) in 1 object(s) allocated from:
    #0 0x55a68c04e867 in __interceptor_strdup (/usr/local/bin/teddycloud+0x64d867)
    #1 0x55a68c1f379f in settings_set_string_id src/settings.c:1411
    #2 0x55a68c1f55b6 in settings_set_string_id src/settings.c:1397
    #3 0x55a68c1f55b6 in settings_set_string src/settings.c:1389
    #4 0x55a68c1f55b6 in settings_init src/settings.c:699
    #5 0x55a68c1ab026 in main_init_settings src/main.c:159
    #6 0x55a68c00db2c in main src/main.c:365
    #7 0x7f00641691c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9)
    #8 0x7f006416928a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a)
    #9 0x55a68c0179d4 in _start (/usr/local/bin/teddycloud+0x6169d4)

Direct leak of 1 byte(s) in 1 object(s) allocated from:
    #0 0x55a68c04e867 in __interceptor_strdup (/usr/local/bin/teddycloud+0x64d867)
    #1 0x55a68c1f379f in settings_set_string_id src/settings.c:1411
    #2 0x55a68c1f55cb in settings_set_string_id src/settings.c:1397
    #3 0x55a68c1f55cb in settings_set_string src/settings.c:1389
    #4 0x55a68c1f55cb in settings_init src/settings.c:700
    #5 0x55a68c1ab026 in main_init_settings src/main.c:159
    #6 0x55a68c00db2c in main src/main.c:365
    #7 0x7f00641691c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9)
    #8 0x7f006416928a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a)
    #9 0x55a68c0179d4 in _start (/usr/local/bin/teddycloud+0x6169d4)

Direct leak of 1 byte(s) in 1 object(s) allocated from:
    #0 0x55a68c04e867 in __interceptor_strdup (/usr/local/bin/teddycloud+0x64d867)
    #1 0x55a68c1f379f in settings_set_string_id src/settings.c:1411
    #2 0x55a68c1f553b in settings_set_string_id src/settings.c:1397
    #3 0x55a68c1f553b in settings_set_string src/settings.c:1389
    #4 0x55a68c1f553b in settings_init src/settings.c:692
    #5 0x55a68c1ab026 in main_init_settings src/main.c:159
    #6 0x55a68c00db2c in main src/main.c:365
    #7 0x7f00641691c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9)
    #8 0x7f006416928a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a)
    #9 0x55a68c0179d4 in _start (/usr/local/bin/teddycloud+0x6169d4)

SUMMARY: AddressSanitizer: 3597 byte(s) leaked in 88 allocation(s).

```

**Comment by SciLor** [comment]
This is completely different topic, as the HASS addon seem not to work at all.
