### ISSUE TITLE
Certificate Generation Fails in Docker Container

### ISSUE THREAD

**Issue by disintegr8te** [toniebox-reverse-engineering/teddycloud#84]
I am encountering an issue with certificate generation when using the TeddyCloud v0.3.2 release. This issue also appears to persist in the v0.3.1 release. I have tested this on a fresh Docker installation on both x64 Ubuntu 22.04 and Windows 11, and the problem remains consistent.

**Environment:**
Operating System: Ubuntu 22.04 (x64) and Windows 11
TeddyCloud Version: v0.3.2 (also confirmed in v0.3.1)

**Steps to Reproduce:**
Install Docker on the respective operating system.
Pull the TeddyCloud Docker image (v0.3.2).
Run the TeddyCloud container

**Expected Behavior:**
The TeddyCloud container should start successfully, and the Server SSL certificates should be generated automatically as mentioned in the project's documentation. https://toniebox-reverse-engineering.github.io/docs/tools/teddycloud/ Point1.2.1
I didn't add the Client Certificates before as this is the next step in the Documentation.

**Actual Behavior:**
When I run the container, I encounter the following errors in the log:

`2023-12-08 12:48:29 teddycloud  | 
2023-12-08 12:48:29 teddycloud  | =================================================================
2023-12-08 12:48:29 teddycloud  | ==9==ERROR: LeakSanitizer: detected memory leaks
2023-12-08 12:48:29 teddycloud  | 
2023-12-08 12:48:29 teddycloud  | Direct leak of 16384 byte(s) in 2 object(s) allocated from:
2023-12-08 12:48:29 teddycloud  |     #0 0x560bf3eb54e7 in malloc (/usr/local/bin/teddycloud+0x5fc4e7)
2023-12-08 12:48:29 teddycloud  |     #1 0x560bf3efd8ce in cert_generate_signed src/cert.c:188
2023-12-08 12:48:29 teddycloud  |     #2 0x560bf4367c1f  (/usr/local/bin/teddycloud+0xaaec1f)
2023-12-08 12:48:29 teddycloud  | 
2023-12-08 12:48:29 teddycloud  | Direct leak of 2384 byte(s) in 2 object(s) allocated from:
2023-12-08 12:48:29 teddycloud  |     #0 0x560bf3eb54e7 in malloc (/usr/local/bin/teddycloud+0x5fc4e7)
2023-12-08 12:48:29 teddycloud  |     #1 0x560bf3efb796 in cert_get_rsa_priv src/cert.c:63
2023-12-08 12:48:29 teddycloud  | 
2023-12-08 12:48:29 teddycloud  | Direct leak of 2286 byte(s) in 2 object(s) allocated from:
2023-12-08 12:48:29 teddycloud  |     #0 0x560bf3eb54e7 in malloc (/usr/local/bin/teddycloud+0x5fc4e7)
2023-12-08 12:48:29 teddycloud  |     #1 0x560bf3efd9f8 in cert_generate_signed src/cert.c:208
2023-12-08 12:48:29 teddycloud  |     #2 0x560bf4367c1f  (/usr/local/bin/teddycloud+0xaaec1f)
2023-12-08 12:48:29 teddycloud  | 
2023-12-08 12:48:29 teddycloud  | Direct leak of 576 byte(s) in 24 object(s) allocated from:
2023-12-08 12:48:29 teddycloud  |     #0 0x560bf3eb54e7 in malloc (/usr/local/bin/teddycloud+0x5fc4e7)
2023-12-08 12:48:29 teddycloud  |     #1 0x560bf3f6d6b6 in mqtt_topic_str src/mqtt.c:86
2023-12-08 12:48:29 teddycloud  | 
2023-12-08 12:48:29 teddycloud  | Direct leak of 354 byte(s) in 12 object(s) allocated from:
2023-12-08 12:48:29 teddycloud  |     #0 0x560bf3eb54e7 in malloc (/usr/local/bin/teddycloud+0x5fc4e7)
2023-12-08 12:48:29 teddycloud  |     #1 0x560bf3f81cb9 in custom_asprintf src/server_helpers.c:39
2023-12-08 12:48:29 teddycloud  | 
2023-12-08 12:48:29 teddycloud  | Direct leak of 162 byte(s) in 12 object(s) allocated from:
2023-12-08 12:48:29 teddycloud  |     #0 0x560bf3eb54e7 in malloc (/usr/local/bin/teddycloud+0x5fc4e7)
2023-12-08 12:48:29 teddycloud  |     #1 0x560bf3f6d52e in mqtt_settingname_clean src/mqtt.c:58
2023-12-08 12:48:29 teddycloud  | 
2023-12-08 12:48:29 teddycloud  | SUMMARY: AddressSanitizer: 22146 byte(s) leaked in 54 allocation(s).
2023-12-08 12:47:42 teddycloud  |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2023-12-08 12:47:42 teddycloud  |                                  Dload  Upload   Total   Spent    Left  Speed
100 3491k  100 3491k    0     0  7142k      0 --:--:-- --:--:-- --:--:-- 7139k
2023-12-08 12:47:44 teddycloud  | TeddyCloud v0.3.2 (50869be) - 2023-12-08 08:09:28 +0000 linux-x86_64
2023-12-08 12:47:44 teddycloud  | 
2023-12-08 12:47:44 teddycloud  | INFO |settings.c:0622:settings_load_ovl| Load settings from config/config.overlay.ini
2023-12-08 12:47:44 teddycloud  | INFO |settings.c:0622:settings_load_ovl| Load settings from config/config.ini
2023-12-08 12:47:44 teddycloud  | ERROR|tls_adapter.c:0193:read_certificate| Failed to open 'certs/server/ca-root.pem' for cert type detection
2023-12-08 12:47:44 teddycloud  | ERROR|tls_adapter.c:0375:load_cert| Loading cert 'certs/server/ca-root.pem' failed
2023-12-08 12:47:44 teddycloud  | INFO |settings.c:1227:settings_load_certs_id| ********************************************
2023-12-08 12:47:44 teddycloud  | INFO |settings.c:1228:settings_load_certs_id|    No certificates found. Generating.
2023-12-08 12:47:44 teddycloud  | INFO |settings.c:1229:settings_load_certs_id|    This will take some time...
2023-12-08 12:47:44 teddycloud  | INFO |settings.c:1230:settings_load_certs_id| ********************************************
2023-12-08 12:47:44 teddycloud  | INFO |cert.c:0396:cert_generate_default| Generating CA certificate...
2023-12-08 12:47:44 teddycloud  | INFO |cert.c:0042:cert_generate_rsa| Generating RSA Key... (slow!)
2023-12-08 12:47:44 teddycloud  | cyclone/cyclone_crypto/cipher/aes.c:260:47: runtime error: left shift of 137 by 24 places cannot be represented in type 'int'
2023-12-08 12:47:44 teddycloud  | cyclone/cyclone_crypto/cipher/aes.c:268:55: runtime error: left shift of 165 by 24 places cannot be represented in type 'int'
2023-12-08 12:47:44 teddycloud  | cyclone/cyclone_crypto/cipher/aes.c:400:34: runtime error: left shift of 132 by 24 places cannot be represented in type 'int'
2023-12-08 12:47:44 teddycloud  | cyclone/cyclone_crypto/cipher/aes.c:385:34: runtime error: left shift of 194 by 24 places cannot be represented in type 'int'
2023-12-08 12:47:44 teddycloud  | cyclone/cyclone_crypto/cipher/aes.c:390:34: runtime error: left shift of 130 by 24 places cannot be represented in type 'int'
2023-12-08 12:47:44 teddycloud  | cyclone/cyclone_crypto/cipher/aes.c:395:34: runtime error: left shift of 168 by 24 places cannot be represented in type 'int'
2023-12-08 12:48:14 teddycloud  | src/cyclone/cyclone_crypto/mpi.c:792:48: runtime error: left shift of 150 by 24 places cannot be represented in type 'int'
2023-12-08 12:48:14 teddycloud  | ERROR|cert.c:0221:cert_generate_signed| fsOpenFile failed
2023-12-08 12:48:14 teddycloud  | ERROR|cert.c:0399:cert_generate_default| cert_generate_signed failed
2023-12-08 12:48:14 teddycloud  | INFO |settings.c:1232:settings_load_certs_id| ********************************************
2023-12-08 12:48:14 teddycloud  | INFO |settings.c:1233:settings_load_certs_id|    FINISHED
2023-12-08 12:48:14 teddycloud  | INFO |settings.c:1234:settings_load_certs_id| ********************************************
2023-12-08 12:48:14 teddycloud  | INFO |settings.c:0622:settings_load_ovl| Load settings from config/config.overlay.ini
2023-12-08 12:48:14 teddycloud  | INFO |tls_adapter.c:0387:tls_adapter_init| Loading certificates...
2023-12-08 12:48:14 teddycloud  | ERROR|tls_adapter.c:0193:read_certificate| Failed to open 'certs/server/ca-root.pem' for cert type detection
2023-12-08 12:48:14 teddycloud  | ERROR|tls_adapter.c:0375:load_cert| Loading cert 'certs/server/ca-root.pem' failed
2023-12-08 12:48:14 teddycloud  | INFO |settings.c:1227:settings_load_certs_id| ********************************************
2023-12-08 12:48:14 teddycloud  | INFO |settings.c:1228:settings_load_certs_id|    No certificates found. Generating.
2023-12-08 12:48:14 teddycloud  | INFO |settings.c:1229:settings_load_certs_id|    This will take some time...
2023-12-08 12:48:14 teddycloud  | INFO |settings.c:1230:settings_load_certs_id| ********************************************
2023-12-08 12:48:14 teddycloud  | INFO |cert.c:0396:cert_generate_default| Generating CA certificate...
2023-12-08 12:48:14 teddycloud  | INFO |cert.c:0042:cert_generate_rsa| Generating RSA Key... (slow!)
2023-12-08 12:48:29 teddycloud  | ERROR|cert.c:0221:cert_generate_signed| fsOpenFile failed
2023-12-08 12:48:29 teddycloud  | ERROR|cert.c:0399:cert_generate_default| cert_generate_signed failed
2023-12-08 12:48:29 teddycloud  | INFO |settings.c:1232:settings_load_certs_id| ********************************************
2023-12-08 12:48:29 teddycloud  | INFO |settings.c:1233:settings_load_certs_id|    FINISHED
2023-12-08 12:48:29 teddycloud  | INFO |settings.c:1234:settings_load_certs_id| ********************************************
2023-12-08 12:48:29 teddycloud  | ERROR|server.c:0427:sanityCheckDir| Config item 'core.certdir' is set to 'certs/client' which was not found
2023-12-08 12:48:29 teddycloud  | ERROR|server.c:0445:sanityChecks| Sanity checks failed, exiting
2023-12-08 12:48:29 teddycloud  | 
2023-12-08 12:48:29 teddycloud  | =================================================================
2023-12-08 12:48:29 teddycloud  | ==9==ERROR: LeakSanitizer: detected memory leaks
2023-12-08 12:48:29 teddycloud  | 
2023-12-08 12:48:29 teddycloud  | Direct leak of 16384 byte(s) in 2 object(s) allocated from:
2023-12-08 12:48:29 teddycloud  |     #0 0x560bf3eb54e7 in malloc (/usr/local/bin/teddycloud+0x5fc4e7)
2023-12-08 12:48:29 teddycloud  |     #1 0x560bf3efd8ce in cert_generate_signed src/cert.c:188
2023-12-08 12:48:29 teddycloud  |     #2 0x560bf4367c1f  (/usr/local/bin/teddycloud+0xaaec1f)
2023-12-08 12:48:29 teddycloud  | 
2023-12-08 12:48:29 teddycloud  | Direct leak of 2384 byte(s) in 2 object(s) allocated from:
2023-12-08 12:48:29 teddycloud  |     #0 0x560bf3eb54e7 in malloc (/usr/local/bin/teddycloud+0x5fc4e7)
2023-12-08 12:48:29 teddycloud  |     #1 0x560bf3efb796 in cert_get_rsa_priv src/cert.c:63
2023-12-08 12:48:29 teddycloud  | 
2023-12-08 12:48:29 teddycloud  | Direct leak of 2286 byte(s) in 2 object(s) allocated from:
2023-12-08 12:48:29 teddycloud  |     #0 0x560bf3eb54e7 in malloc (/usr/local/bin/teddycloud+0x5fc4e7)
2023-12-08 12:48:29 teddycloud  |     #1 0x560bf3efd9f8 in cert_generate_signed src/cert.c:208
2023-12-08 12:48:29 teddycloud  |     #2 0x560bf4367c1f  (/usr/local/bin/teddycloud+0xaaec1f)
2023-12-08 12:48:29 teddycloud  | 
2023-12-08 12:48:29 teddycloud  | Direct leak of 576 byte(s) in 24 object(s) allocated from:
2023-12-08 12:48:29 teddycloud  |     #0 0x560bf3eb54e7 in malloc (/usr/local/bin/teddycloud+0x5fc4e7)
2023-12-08 12:48:29 teddycloud  |     #1 0x560bf3f6d6b6 in mqtt_topic_str src/mqtt.c:86
2023-12-08 12:48:29 teddycloud  | 
2023-12-08 12:48:29 teddycloud  | Direct leak of 354 byte(s) in 12 object(s) allocated from:
2023-12-08 12:48:29 teddycloud  |     #0 0x560bf3eb54e7 in malloc (/usr/local/bin/teddycloud+0x5fc4e7)
2023-12-08 12:48:29 teddycloud  |     #1 0x560bf3f81cb9 in custom_asprintf src/server_helpers.c:39
2023-12-08 12:48:29 teddycloud  | 
2023-12-08 12:48:29 teddycloud  | Direct leak of 162 byte(s) in 12 object(s) allocated from:
2023-12-08 12:48:29 teddycloud  |     #0 0x560bf3eb54e7 in malloc (/usr/local/bin/teddycloud+0x5fc4e7)
2023-12-08 12:48:29 teddycloud  |     #1 0x560bf3f6d52e in mqtt_settingname_clean src/mqtt.c:58
2023-12-08 12:48:29 teddycloud  | `

These errors indicate that the certificate generation process is encountering issues, particularly related to RSA key generation and file operations, even though it should be automated when using Docker.

**Comment by disintegr8te** [comment]
Found the Docker hints, Issue can be closed.
"The container won’t run without the flash:/cert/ca.der (Boxine CA), flash:/cert/client.der (Client Cert) and flash:/cert/private.der (Client private key)."

**Comment by SciLor** [comment]
Thank you for posting your solution. I think this is something we should change. The container should boot without.
