### ISSUE TITLE
TEddycloud Docker Image exits after some days of being up and running

### ISSUE THREAD

**Issue by mptr8956** [toniebox-reverse-engineering/teddycloud#93]
Exits with the following error, after a restart, it works again!

INFO |server.c:0583:server_init| Exiting TeddyCloud with returncode -3
=================================================================
==9==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 72773 byte(s) in 4644 object(s) allocated from:
    #0 0x55683c1f5627 in strdup (/usr/local/bin/teddycloud+0x5a3627)
    #1 0x55683c346c58 in tonies_readJson src/toniesJson.c:124
Direct leak of 17550 byte(s) in 4644 object(s) allocated from:
    #0 0x55683c1f5627 in strdup (/usr/local/bin/teddycloud+0x5a3627)
    #1 0x55683c346c9b in tonies_readJson src/toniesJson.c:126
Direct leak of 4932 byte(s) in 14 object(s) allocated from:
    #0 0x55683c24e4e7 in malloc (/usr/local/bin/teddycloud+0x5fc4e7)
    #1 0x55683c31acb9 in custom_asprintf src/server_helpers.c:39
Direct leak of 576 byte(s) in 24 object(s) allocated from:
    #0 0x55683c24e4e7 in malloc (/usr/local/bin/teddycloud+0x5fc4e7)
    #1 0x55683c3066b6 in mqtt_topic_str src/mqtt.c:86
Direct leak of 162 byte(s) in 12 object(s) allocated from:
    #0 0x55683c24e4e7 in malloc (/usr/local/bin/teddycloud+0x5fc4e7)
    #1 0x55683c30652e in mqtt_settingname_clean src/mqtt.c:58
SUMMARY: AddressSanitizer: 95993 byte(s) leaked in 9338 allocation(s).

**Comment by mptr8956** [comment]
hi, 0.3.2. sorry, already restarted the container, the lines before are lost. will come up with the additional info as soon as it crashes again (probably some days)

**Comment by mptr8956** [comment]
Hi, exited just before christmas, but the log is quite short. How can I access the full log? 
[_teddycloud_logs (2).txt](https://github.com/toniebox-reverse-engineering/teddycloud/files/13803874/_teddycloud_logs.2.txt)

**Comment by SciLor** [comment]
This looks really weird, as it seems that the certs volume / certs seems
 to be gone.

**Comment by mptr8956** [comment]
strange, both dirs are existing (and as soon as i restart teddycloud, everything works as expected)
